// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mcp/v1alpha1/resource.proto

package istio.mcp.v1alpha1;

public final class ResourceOuterClass {
  private ResourceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResourceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:istio.mcp.v1alpha1.Resource)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Common metadata describing the resource.
     * </pre>
     *
     * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    boolean hasMetadata();
    /**
     * <pre>
     * Common metadata describing the resource.
     * </pre>
     *
     * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
     * @return The metadata.
     */
    istio.mcp.v1alpha1.MetadataOuterClass.Metadata getMetadata();
    /**
     * <pre>
     * Common metadata describing the resource.
     * </pre>
     *
     * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
     */
    istio.mcp.v1alpha1.MetadataOuterClass.MetadataOrBuilder getMetadataOrBuilder();

    /**
     * <pre>
     * The primary payload for the resource.
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return Whether the body field is set.
     */
    boolean hasBody();
    /**
     * <pre>
     * The primary payload for the resource.
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return The body.
     */
    com.google.protobuf.Any getBody();
    /**
     * <pre>
     * The primary payload for the resource.
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getBodyOrBuilder();
  }
  /**
   * <pre>
   * Resource as transferred via the Mesh Configuration Protocol. Each
   * resource is made up of common metadata, and a type-specific resource payload.
   * </pre>
   *
   * Protobuf type {@code istio.mcp.v1alpha1.Resource}
   */
  public static final class Resource extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:istio.mcp.v1alpha1.Resource)
      ResourceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Resource.newBuilder() to construct.
    private Resource(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Resource() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Resource();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return istio.mcp.v1alpha1.ResourceOuterClass.internal_static_istio_mcp_v1alpha1_Resource_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return istio.mcp.v1alpha1.ResourceOuterClass.internal_static_istio_mcp_v1alpha1_Resource_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              istio.mcp.v1alpha1.ResourceOuterClass.Resource.class, istio.mcp.v1alpha1.ResourceOuterClass.Resource.Builder.class);
    }

    public static final int METADATA_FIELD_NUMBER = 1;
    private istio.mcp.v1alpha1.MetadataOuterClass.Metadata metadata_;
    /**
     * <pre>
     * Common metadata describing the resource.
     * </pre>
     *
     * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
     * @return Whether the metadata field is set.
     */
    @java.lang.Override
    public boolean hasMetadata() {
      return metadata_ != null;
    }
    /**
     * <pre>
     * Common metadata describing the resource.
     * </pre>
     *
     * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
     * @return The metadata.
     */
    @java.lang.Override
    public istio.mcp.v1alpha1.MetadataOuterClass.Metadata getMetadata() {
      return metadata_ == null ? istio.mcp.v1alpha1.MetadataOuterClass.Metadata.getDefaultInstance() : metadata_;
    }
    /**
     * <pre>
     * Common metadata describing the resource.
     * </pre>
     *
     * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
     */
    @java.lang.Override
    public istio.mcp.v1alpha1.MetadataOuterClass.MetadataOrBuilder getMetadataOrBuilder() {
      return metadata_ == null ? istio.mcp.v1alpha1.MetadataOuterClass.Metadata.getDefaultInstance() : metadata_;
    }

    public static final int BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.Any body_;
    /**
     * <pre>
     * The primary payload for the resource.
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return Whether the body field is set.
     */
    @java.lang.Override
    public boolean hasBody() {
      return body_ != null;
    }
    /**
     * <pre>
     * The primary payload for the resource.
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     * @return The body.
     */
    @java.lang.Override
    public com.google.protobuf.Any getBody() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }
    /**
     * <pre>
     * The primary payload for the resource.
     * </pre>
     *
     * <code>.google.protobuf.Any body = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
      return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (metadata_ != null) {
        output.writeMessage(1, getMetadata());
      }
      if (body_ != null) {
        output.writeMessage(2, getBody());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (metadata_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMetadata());
      }
      if (body_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getBody());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof istio.mcp.v1alpha1.ResourceOuterClass.Resource)) {
        return super.equals(obj);
      }
      istio.mcp.v1alpha1.ResourceOuterClass.Resource other = (istio.mcp.v1alpha1.ResourceOuterClass.Resource) obj;

      if (hasMetadata() != other.hasMetadata()) return false;
      if (hasMetadata()) {
        if (!getMetadata()
            .equals(other.getMetadata())) return false;
      }
      if (hasBody() != other.hasBody()) return false;
      if (hasBody()) {
        if (!getBody()
            .equals(other.getBody())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMetadata()) {
        hash = (37 * hash) + METADATA_FIELD_NUMBER;
        hash = (53 * hash) + getMetadata().hashCode();
      }
      if (hasBody()) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBody().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(istio.mcp.v1alpha1.ResourceOuterClass.Resource prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Resource as transferred via the Mesh Configuration Protocol. Each
     * resource is made up of common metadata, and a type-specific resource payload.
     * </pre>
     *
     * Protobuf type {@code istio.mcp.v1alpha1.Resource}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:istio.mcp.v1alpha1.Resource)
        istio.mcp.v1alpha1.ResourceOuterClass.ResourceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return istio.mcp.v1alpha1.ResourceOuterClass.internal_static_istio_mcp_v1alpha1_Resource_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return istio.mcp.v1alpha1.ResourceOuterClass.internal_static_istio_mcp_v1alpha1_Resource_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                istio.mcp.v1alpha1.ResourceOuterClass.Resource.class, istio.mcp.v1alpha1.ResourceOuterClass.Resource.Builder.class);
      }

      // Construct using istio.mcp.v1alpha1.ResourceOuterClass.Resource.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        metadata_ = null;
        if (metadataBuilder_ != null) {
          metadataBuilder_.dispose();
          metadataBuilder_ = null;
        }
        body_ = null;
        if (bodyBuilder_ != null) {
          bodyBuilder_.dispose();
          bodyBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return istio.mcp.v1alpha1.ResourceOuterClass.internal_static_istio_mcp_v1alpha1_Resource_descriptor;
      }

      @java.lang.Override
      public istio.mcp.v1alpha1.ResourceOuterClass.Resource getDefaultInstanceForType() {
        return istio.mcp.v1alpha1.ResourceOuterClass.Resource.getDefaultInstance();
      }

      @java.lang.Override
      public istio.mcp.v1alpha1.ResourceOuterClass.Resource build() {
        istio.mcp.v1alpha1.ResourceOuterClass.Resource result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public istio.mcp.v1alpha1.ResourceOuterClass.Resource buildPartial() {
        istio.mcp.v1alpha1.ResourceOuterClass.Resource result = new istio.mcp.v1alpha1.ResourceOuterClass.Resource(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(istio.mcp.v1alpha1.ResourceOuterClass.Resource result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.metadata_ = metadataBuilder_ == null
              ? metadata_
              : metadataBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.body_ = bodyBuilder_ == null
              ? body_
              : bodyBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof istio.mcp.v1alpha1.ResourceOuterClass.Resource) {
          return mergeFrom((istio.mcp.v1alpha1.ResourceOuterClass.Resource)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(istio.mcp.v1alpha1.ResourceOuterClass.Resource other) {
        if (other == istio.mcp.v1alpha1.ResourceOuterClass.Resource.getDefaultInstance()) return this;
        if (other.hasMetadata()) {
          mergeMetadata(other.getMetadata());
        }
        if (other.hasBody()) {
          mergeBody(other.getBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getMetadataFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getBodyFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private istio.mcp.v1alpha1.MetadataOuterClass.Metadata metadata_;
      private com.google.protobuf.SingleFieldBuilderV3<
          istio.mcp.v1alpha1.MetadataOuterClass.Metadata, istio.mcp.v1alpha1.MetadataOuterClass.Metadata.Builder, istio.mcp.v1alpha1.MetadataOuterClass.MetadataOrBuilder> metadataBuilder_;
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       * @return Whether the metadata field is set.
       */
      public boolean hasMetadata() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       * @return The metadata.
       */
      public istio.mcp.v1alpha1.MetadataOuterClass.Metadata getMetadata() {
        if (metadataBuilder_ == null) {
          return metadata_ == null ? istio.mcp.v1alpha1.MetadataOuterClass.Metadata.getDefaultInstance() : metadata_;
        } else {
          return metadataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      public Builder setMetadata(istio.mcp.v1alpha1.MetadataOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          metadata_ = value;
        } else {
          metadataBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      public Builder setMetadata(
          istio.mcp.v1alpha1.MetadataOuterClass.Metadata.Builder builderForValue) {
        if (metadataBuilder_ == null) {
          metadata_ = builderForValue.build();
        } else {
          metadataBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      public Builder mergeMetadata(istio.mcp.v1alpha1.MetadataOuterClass.Metadata value) {
        if (metadataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            metadata_ != null &&
            metadata_ != istio.mcp.v1alpha1.MetadataOuterClass.Metadata.getDefaultInstance()) {
            getMetadataBuilder().mergeFrom(value);
          } else {
            metadata_ = value;
          }
        } else {
          metadataBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      public Builder clearMetadata() {
        bitField0_ = (bitField0_ & ~0x00000001);
        metadata_ = null;
        if (metadataBuilder_ != null) {
          metadataBuilder_.dispose();
          metadataBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      public istio.mcp.v1alpha1.MetadataOuterClass.Metadata.Builder getMetadataBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getMetadataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      public istio.mcp.v1alpha1.MetadataOuterClass.MetadataOrBuilder getMetadataOrBuilder() {
        if (metadataBuilder_ != null) {
          return metadataBuilder_.getMessageOrBuilder();
        } else {
          return metadata_ == null ?
              istio.mcp.v1alpha1.MetadataOuterClass.Metadata.getDefaultInstance() : metadata_;
        }
      }
      /**
       * <pre>
       * Common metadata describing the resource.
       * </pre>
       *
       * <code>.istio.mcp.v1alpha1.Metadata metadata = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          istio.mcp.v1alpha1.MetadataOuterClass.Metadata, istio.mcp.v1alpha1.MetadataOuterClass.Metadata.Builder, istio.mcp.v1alpha1.MetadataOuterClass.MetadataOrBuilder> 
          getMetadataFieldBuilder() {
        if (metadataBuilder_ == null) {
          metadataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              istio.mcp.v1alpha1.MetadataOuterClass.Metadata, istio.mcp.v1alpha1.MetadataOuterClass.Metadata.Builder, istio.mcp.v1alpha1.MetadataOuterClass.MetadataOrBuilder>(
                  getMetadata(),
                  getParentForChildren(),
                  isClean());
          metadata_ = null;
        }
        return metadataBuilder_;
      }

      private com.google.protobuf.Any body_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> bodyBuilder_;
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       * @return Whether the body field is set.
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       * @return The body.
       */
      public com.google.protobuf.Any getBody() {
        if (bodyBuilder_ == null) {
          return body_ == null ? com.google.protobuf.Any.getDefaultInstance() : body_;
        } else {
          return bodyBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body_ = value;
        } else {
          bodyBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder setBody(
          com.google.protobuf.Any.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          body_ = builderForValue.build();
        } else {
          bodyBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder mergeBody(com.google.protobuf.Any value) {
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            body_ != null &&
            body_ != com.google.protobuf.Any.getDefaultInstance()) {
            getBodyBuilder().mergeFrom(value);
          } else {
            body_ = value;
          }
        } else {
          bodyBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = null;
        if (bodyBuilder_ != null) {
          bodyBuilder_.dispose();
          bodyBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.Any.Builder getBodyBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBodyFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getBodyOrBuilder() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilder();
        } else {
          return body_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : body_;
        }
      }
      /**
       * <pre>
       * The primary payload for the resource.
       * </pre>
       *
       * <code>.google.protobuf.Any body = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getBody(),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:istio.mcp.v1alpha1.Resource)
    }

    // @@protoc_insertion_point(class_scope:istio.mcp.v1alpha1.Resource)
    private static final istio.mcp.v1alpha1.ResourceOuterClass.Resource DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new istio.mcp.v1alpha1.ResourceOuterClass.Resource();
    }

    public static istio.mcp.v1alpha1.ResourceOuterClass.Resource getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Resource>
        PARSER = new com.google.protobuf.AbstractParser<Resource>() {
      @java.lang.Override
      public Resource parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Resource> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Resource> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public istio.mcp.v1alpha1.ResourceOuterClass.Resource getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_istio_mcp_v1alpha1_Resource_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_istio_mcp_v1alpha1_Resource_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033mcp/v1alpha1/resource.proto\022\022istio.mcp" +
      ".v1alpha1\032\031google/protobuf/any.proto\032\024go" +
      "goproto/gogo.proto\032\033mcp/v1alpha1/metadat" +
      "a.proto\"^\n\010Resource\022.\n\010metadata\030\001 \001(\0132\034." +
      "istio.mcp.v1alpha1.Metadata\022\"\n\004body\030\002 \001(" +
      "\0132\024.google.protobuf.AnyB\037Z\031istio.io/api/" +
      "mcp/v1alpha1\250\342\036\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.GoGoProtos.getDescriptor(),
          istio.mcp.v1alpha1.MetadataOuterClass.getDescriptor(),
        });
    internal_static_istio_mcp_v1alpha1_Resource_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_istio_mcp_v1alpha1_Resource_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_istio_mcp_v1alpha1_Resource_descriptor,
        new java.lang.String[] { "Metadata", "Body", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.GoGoProtos.equalAll);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.GoGoProtos.getDescriptor();
    istio.mcp.v1alpha1.MetadataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
